<#
.SYNOPSIS
Recompiles every routine the title carries inside its audio banks.

.DESCRIPTION
All 158 banks on the disc embed a small MIPS routine that the sound engine
calls, and none of them are in the module, so none are in the AOT corpus. Doing
them one at a time as the game runs into them works - the profile prints the
fingerprint of anything it does not recognise - but each one costs a stop, a
rebuild and a fresh boot.

This does the lot in one pass. Banks that carry the same routine share a unit:
the fingerprint is of the routine before linking, which is how it arrives in
memory, so identical routines collapse to one translation unit no matter how
many banks contain them.

The result is a generated include listing every routine, which defjam_banks.cpp
turns into both the declarations and the lookup table, so nothing has to be
kept in step by hand.

Requires a staged game and a built psp_recomp and defjam_extract_bank_code.
Nothing it reads or writes belongs in the repository except the generated code.

.EXAMPLE
./recompile_bank_code.ps1
./recompile_bank_code.ps1 -WhatIfOnly
#>
[CmdletBinding()]
param(
    [string]$ExportTable = "0x08AE1418",
    [uint32]$FirstUnit = 400,
    [switch]$WhatIfOnly
)

$ErrorActionPreference = "Stop"

$profileDir = Split-Path -Parent $PSScriptRoot
$root = Split-Path -Parent (Split-Path -Parent $profileDir)
$extract = Join-Path $root "out/defjam/bin/Release/defjam_extract_bank_code.exe"
$recomp = Join-Path $root "out/framework/Release/psp_recomp.exe"
$boot = Join-Path $profileDir "game/PSP_GAME/SYSDIR/BOOT.BIN"
$generated = Join-Path $profileDir "generated"
$banks = Join-Path $profileDir "game/PSP_GAME/USRDIR"

foreach ($needed in @($extract, $recomp, $boot)) {
    if (-not (Test-Path $needed)) { Write-Error "missing: $needed" }
}

# The routines are position independent once linked, so the address they are
# generated at is a label-naming detail rather than a promise; the runtime is
# told where each one really is when the bank loads.
$nominalBase = "0x09000000"

$staging = Join-Path ([System.IO.Path]::GetTempPath()) "defjam_bank_code"
New-Item -ItemType Directory -Force -Path $staging | Out-Null

$files = Get-ChildItem -Path $banks -Filter *.abk -Recurse | Sort-Object Name
Write-Host "$($files.Count) audio banks found"

$byFingerprint = [ordered]@{}
$rejected = 0
$unit = $FirstUnit

foreach ($file in $files) {
    $linked = Join-Path $staging "linked.bin"
    $report = & $extract $boot $ExportTable $file.FullName $linked 2>&1
    if ($LASTEXITCODE -ne 0) {
        $rejected++
        Write-Host "  rejected  $($file.Name): $($report | Select-Object -Last 1)" -ForegroundColor Yellow
        continue
    }

    $fingerprint = ($report | Select-String -Pattern 'fingerprint:\s+(0x[0-9A-F]+)').Matches.Groups[1].Value
    if ([string]::IsNullOrEmpty($fingerprint)) {
        $rejected++
        Write-Host "  no fingerprint for $($file.Name)" -ForegroundColor Yellow
        continue
    }

    if ($byFingerprint.Contains($fingerprint)) {
        $byFingerprint[$fingerprint].Banks += $file.Name
        continue
    }

    $symbol = "recomp_unit_{0:d4}" -f $unit
    $byFingerprint[$fingerprint] = [pscustomobject]@{
        Unit   = $unit
        Symbol = $symbol
        Banks  = @($file.Name)
    }

    if (-not $WhatIfOnly) {
        $keep = Join-Path $staging "$symbol.bin"
        Copy-Item $linked $keep -Force
        & $recomp --relocatable $keep $nominalBase $unit $generated | Out-Null
        if ($LASTEXITCODE -ne 0) { Write-Error "psp_recomp failed on $($file.Name)" }
    }
    $unit++
}

Write-Host ""
Write-Host "$($byFingerprint.Count) distinct routines, $rejected bank(s) this tool could not read"
if ($byFingerprint.Count -gt 0) {
    $last = $FirstUnit + $byFingerprint.Count - 1
    Write-Host "units $FirstUnit..$last"
}
if ($WhatIfOnly) { return }

# One line per routine, expanded twice by defjam_banks.cpp: once into the
# declarations and once into the table. Keeping both from the same list is what
# stops them drifting apart.
$lines = @(
    "// Generated by recompile_bank_code.ps1. Do not edit.",
    "//",
    "// One line per routine the title carries in its audio banks: the",
    "// fingerprint of the routine as it arrives in memory, the unit it was",
    "// recompiled into, and a bank it appears in.",
    ""
)
foreach ($entry in $byFingerprint.GetEnumerator()) {
    $name = $entry.Value.Banks[0]
    $shared = if ($entry.Value.Banks.Count -gt 1) { " and $($entry.Value.Banks.Count - 1) more" } else { "" }
    $lines += "BANK_ROUTINE($($entry.Key)ull, $($entry.Value.Symbol), `"$name$shared`")"
}
$target = Join-Path $generated "generated_bank_routines.inc"
Set-Content -Path $target -Value $lines -Encoding utf8
Write-Host "wrote $target"
